# Generated by hand_gesture_recorder; edit only if you know the protocol.
HAND = 'L10'
GESTURES = {0: [254.0, 127.0, 254.0, 254.0, 254.0, 254.0, 0.0, 29.0, 0.0, 124.0], 1: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 2: [255.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 5.0, 0.0, 124.0]}

def pose(number):
    return list(GESTURES[number])
