# Generated by hand_gesture_recorder; edit only if you know the protocol.
HAND = 'O6'
GESTURES = {0: [100.0, 99.6078431372549, 99.6078431372549, 99.6078431372549, 99.6078431372549, 99.6078431372549], 1: [51.0, 53.6078431372549, 0.0, 0.0, 0.0, 0.0], 2: [100.0, 0.0, 0.0, 0.0, 0.0, 0.0]}

def pose(number):
    return list(GESTURES[number])
