# Generated by hand_gesture_recorder; edit only if you know the protocol.
HAND = 'O6'
GESTURES = {0: [100.0, 100.0, 99.6078431372549, 99.6078431372549, 99.6078431372549, 99.6078431372549], 1: [22.0, 73.0, 0.0, 0.0, 0.0, 0.0], 2: [19.0, 31.0, 56.0, 0.0, 100.0, 100.0], 3: [17.0, 31.0, 56.0, 100.0, 100.0, 100.0]}

def pose(number):
    return list(GESTURES[number])
