# Generated by hand_gesture_recorder; edit only if you know the protocol.
HAND = 'O6'
GESTURES = {0: [100.0, 100.0, 99.6078431372549, 99.2156862745098, 99.2156862745098, 99.2156862745098], 1: [100.0, 0.0, 0.0, 0.0, 0.0, 0.0], 2: [46.0, 30.0, 46.0, 100.0, 100.0, 100.0], 3: [60.0, 24.0, 12.0, 7.0, 0.0, 0.0]}

def pose(number):
    return list(GESTURES[number])
