"""Stable, importable gesture storage (no hardware dependencies)."""
from __future__ import annotations

from dataclasses import dataclass, field
import json
from pathlib import Path
from typing import Sequence


@dataclass
class GestureSet:
    hand: str
    gestures: dict[int, list[float]] = field(default_factory=dict)

    def add(self, number: int, values: Sequence[float]) -> None:
        if number < 0 or len(values) not in (6, 10):
            raise ValueError("gesture number must be non-negative and pose must have 6 or 10 values")
        self.gestures[int(number)] = [float(v) for v in values]

    def export(self, directory: str | Path, *, stem: str | None = None) -> tuple[Path, Path]:
        out = Path(directory); out.mkdir(parents=True, exist_ok=True)
        stem = stem or f"{self.hand.lower()}_gestures"
        py = out / f"{stem}.py"
        js = out / f"{stem}.json"
        ordered = {k: self.gestures[k] for k in sorted(self.gestures)}
        py.write_text("# Generated by hand_gesture_recorder; edit only if you know the protocol.\n"
                      f"HAND = {self.hand!r}\nGESTURES = {ordered!r}\n\n"
                      "def pose(number):\n    return list(GESTURES[number])\n", encoding="utf-8")
        js.write_text(json.dumps({"hand": self.hand, "gestures": ordered}, indent=2) + "\n", encoding="utf-8")
        return py, js


class GestureFile:
    """Load a generated gesture module without importing arbitrary code."""
    @staticmethod
    def load_json(path: str | Path) -> GestureSet:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        result = GestureSet(str(data["hand"]))
        for key, values in data["gestures"].items(): result.add(int(key), values)
        return result
