name: mpc_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pip
  - pip:
      - pin>=4.0,<5
      - pin-pink>=4.3,<5
      - meshcat>=0.3,<0.4
      - dex-retargeting>=0.5,<0.6
      - mediapipe>=0.10,<0.11
      - pyrealsense2>=2.57,<2.58
      - qpsolvers>=4.0,<5
