#!/usr/bin/env python3
"""Produce visual and convex-decomposed collision meshes on the GPU worker."""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import coacd
import numpy as np


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_blender_script(path: Path, source: Path, visual: Path) -> None:
    path.write_text(
        "import bpy\n"
        "bpy.ops.object.select_all(action='SELECT')\n"
        "bpy.ops.object.delete(use_global=False)\n"
        f"source = {str(source)!r}\n"
        f"visual = {str(visual)!r}\n"
        "suffix = source.rsplit('.', 1)[-1].lower()\n"
        "loaders = {'obj': bpy.ops.wm.obj_import, 'stl': bpy.ops.wm.stl_import, 'ply': bpy.ops.wm.ply_import, 'glb': bpy.ops.import_scene.gltf, 'gltf': bpy.ops.import_scene.gltf}\n"
        "if suffix not in loaders: raise RuntimeError('unsupported mesh format: ' + suffix)\n"
        "loaders[suffix](filepath=source)\n"
        "for obj in list(bpy.context.scene.objects):\n"
        "    if obj.type != 'MESH': continue\n"
        "    bpy.context.view_layer.objects.active = obj\n"
        "    obj.select_set(True)\n"
        "    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)\n"
        "    triangulate = obj.modifiers.new(name='triangulate', type='TRIANGULATE')\n"
        "    bpy.ops.object.modifier_apply(modifier=triangulate.name)\n"
        "    obj.select_set(False)\n"
        "bpy.ops.object.select_all(action='SELECT')\n"
        "bpy.ops.wm.obj_export(filepath=visual, export_materials=False)\n",
        encoding="utf-8",
    )


def load_obj(path: Path) -> tuple[np.ndarray, np.ndarray]:
    vertices: list[list[float]] = []
    faces: list[list[int]] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        fields = line.split()
        if not fields:
            continue
        if fields[0] == "v":
            vertices.append([float(value) for value in fields[1:4]])
        elif fields[0] == "f":
            face = [int(token.split("/")[0]) - 1 for token in fields[1:]]
            for index in range(1, len(face) - 1):
                faces.append([face[0], face[index], face[index + 1]])
    if not vertices or not faces:
        raise ValueError(f"OBJ contains no triangular mesh: {path}")
    return np.asarray(vertices, dtype=np.float64), np.asarray(faces, dtype=np.int32)


def write_obj(path: Path, parts: list[list[np.ndarray]]) -> None:
    offset = 0
    lines = ["# Convex decomposition generated by CoACD; collision-only.\n"]
    for part_index, (vertices, triangles) in enumerate(parts):
        lines.append(f"o convex_part_{part_index}\n")
        for vertex in vertices:
            lines.append(f"v {vertex[0]:.9g} {vertex[1]:.9g} {vertex[2]:.9g}\n")
        for triangle in triangles:
            indices = [int(value) + 1 + offset for value in triangle]
            lines.append(f"f {indices[0]} {indices[1]} {indices[2]}\n")
        offset += len(vertices)
    path.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--name", help="asset stem; defaults to input stem")
    parser.add_argument("--coacd-threshold", type=float, default=0.05)
    parser.add_argument("--max-convex-hull", type=int, default=32)
    args = parser.parse_args()
    if not args.input.is_file():
        raise SystemExit(f"input asset not found: {args.input}")
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    required = ("source_url", "license", "attribution", "scale_to_meters", "used_for")
    missing = [key for key in required if key not in manifest]
    if missing:
        raise SystemExit("manifest missing: " + ", ".join(missing))
    if manifest["used_for"] != "visual_only":
        raise SystemExit("downloaded visual assets must declare used_for: visual_only")
    if not 0 < args.coacd_threshold <= 1:
        raise SystemExit("--coacd-threshold must be in (0, 1]")

    asset_name = args.name or args.input.stem
    visual_dir, collision_dir, manifest_dir = (args.output / item for item in ("visual", "collision", "manifests"))
    for directory in (visual_dir, collision_dir, manifest_dir):
        directory.mkdir(parents=True, exist_ok=True)
    visual = visual_dir / f"{asset_name}.obj"
    collision = collision_dir / f"{asset_name}_coacd.obj"
    with tempfile.TemporaryDirectory(prefix="connector_asset_") as tmp:
        script = Path(tmp) / "prepare_visual.py"
        write_blender_script(script, args.input.resolve(), visual.resolve())
        subprocess.run(["blender", "--background", "--python", str(script)], check=True)
    vertices, faces = load_obj(visual)
    parts = coacd.run_coacd(coacd.Mesh(vertices, faces), threshold=args.coacd_threshold, max_convex_hull=args.max_convex_hull)
    write_obj(collision, parts)
    generated = {
        **manifest,
        "retrieved_at": manifest.get("retrieved_at", datetime.now(timezone.utc).isoformat()),
        "source_sha256": sha256(args.input),
        "visual_sha256": sha256(visual),
        "collision_sha256": sha256(collision),
        "collision_generator": {"tool": "CoACD", "threshold": args.coacd_threshold, "max_convex_hull": args.max_convex_hull, "part_count": len(parts)},
    }
    manifest_path = manifest_dir / f"{asset_name}.manifest.json"
    manifest_path.write_text(json.dumps(generated, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"visual_asset": str(visual), "collision_asset": str(collision), "manifest": str(manifest_path), "convex_parts": len(parts), "passed": True}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
